### ISSUE TITLE
Agregar temperatura de macerado a impresión

### ISSUE THREAD

**Issue by federicociro** [lautarobock/brew-o-matic#158]
Sería muy útil tener algunos parametros de maceración, tiempos y temperaturas en la hoja de impresión.
Gracias totales por este GIT.

**Comment by lautarobock** [comment]
Buenas, gracias por aportar al proyecto :-) 
te comento q x ahora estoy con muy poco tiempo para dedicarle, pero cuando retome parte de lo importante es justamente mejorar el tema de la impresion. 

De todas formas, simpre mi foco estuvo puesto en tratar de no imprimir y poder trabajar directamente desde la aplicacion. 
Si se te complica el dia de la coccion, fijate que desde al app (android y ios) podes tener bajadas las recetas y no necesitas conexion para verlas

**Comment by fedehtm** [comment]
Gracias Lautaro, muy atento.
Muchos de nosotros te debemos una cuota de nuestras cervezas por tanto
tiempo que nos ahorras.

De paso te consulto, te interesaría poner alguna publicidad, o link en la
web hacia una tienda de insumos para cerveza?
Hace tiempo deje de hacer cerveza comercialmente, y me dedico a vender
insumos con Vera Cruz <https://www.veracruzinsumos.com.ar/>.
El desarrollo del negocio y de la web es a puro lomo, hoy ya tengo
estabilizado lo que es el flow de ventas, el SEM y otras cosas importantes
que faltaban.
Ahora estoy buscando mejorar el SEO orgánico, es por eso que me interesaría
(más que publicidad) tener un link en tu web/app, no se si estas
interesado, yo recién estoy comenzando.
Gracias desde ya por todo.

Saludos, Federico

**Comment by lautarobock** [comment]
Hola, 

No estoy aceptando publicidad (ni similares). Al estar vinculado con la asociacion civil Somos Cerveceros queda mal si pongo publicida. No tenemos ningun vinculo comercial, y el BoM es 100% pero como lo publicamos como herramienta oficial de SC puede verse feo si se hace publicidad y si encima se piensa que las ganancias pueden ser para mi (un particular)

**Comment by fedehtm** [comment]
Te entiendo Lautaro, gracias desde ya por la atención y que tengas buenas
birras!
Felicitaciones si no te lo dije antes.
Saludos, Federico
